steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'app/Dockerfile', '-t', 'us-docker.pkg.dev/biology-multimodal-2026/docker/tcga_rna_model:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/biology-multimodal-2026/docker/tcga_rna_model:latest']
images:
  - 'us-docker.pkg.dev/biology-multimodal-2026/docker/tcga_rna_model:latest'